### ISSUE TITLE
For a future Pull Request:

### ISSUE THREAD

**Issue by xanaguy** [segabl/pd2-kill-feed#10]
bank_manager = { default = "Manager", dah = "Ralph Garnet" }

Using WolfHUD's "EnemyHealth" coding, I was able to get your mod to differentiate between First World Bank's Manager from Ralph Garnet. However, the second I killed him caused a crash: 

mods/KillFeed/killfeed.lua:80: attempt to concatenate field 'name' (a table value)

SCRIPT STACK

new() core/lib/utils/coreclass.lua:35
add_kill() @mods/KillFeed/killfeed.lua:304
_on_damage_received() @mods/KillFeed/killfeed.lua:401
damage_bullet() lib/units/enemies/cop/copdamage.lua:597
give_impact_damage() lib/units/weapons/raycastweaponbase.lua:2164
on_collision() lib/units/weapons/raycastweaponbase.lua:2077
_fire_raycast() lib/units/weapons/shotgun/shotgunbase.lua:287
fire_original() lib/units/weapons/raycastweaponbase.lua:459
fire() @mods/WolfHUD/lua/BurstFire.lua:89
trigger_pressed() lib/units/weapons/raycastweaponbase.lua:356
_check_action_primary_attack() lib/units/beings/player/states/playerstandard.lua:4690
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:886
update_original() lib/units/beings/player/states/playerstandard.lua:414
master_PlayerStandard_update() @mods/WolfHUD/lua/BurstFire.lua:212
original() @mods/Carry Stacker Reloaded/lua/playerstandard.lua:7
update() @mods/base/req/core/Hooks.lua:260
lib/units/beings/player/playermovement.lua:275

This is basically an idea for the Diamond Heist so Kill Feed doesn't confuse Ralph for the Bank Manager. Is there anything I can do from here to ensure working conditions? Lastly, I plan on adding every possible unit simply for Quality of Life (for different risk levels). Do you have a list of the internal names of the standard enemies?

**Comment by segabl** [comment]
Simply putting `bank_manager = { default = "Manager", dah = "Ralph Garnet" }` won't work because the current code expects a string value. It's not a difficult task to change it if you know some LUA. I might add that in the future.
Regarding unit names, everything that's not defined in the file is basically the internal name with spaces instead of underlines and capitalized words. The ids are contained in [charactertweakdata.lua](https://bitbucket.org/TdlQ/payday-2-luajit/src/0f18c60905da6bd1aeffe8cbf23c50a88c1691f4/lib/tweak_data/charactertweakdata.lua?at=default&fileviewer=file-view-default)

**Comment by segabl** [comment]
I have now added support for setting character names based on heist, let me know if this is enough for you to work with. It's only on GitHub so far.

**Comment by xanaguy** [comment]
That was unfortunately the only thing I wanted to do (just Ralph Garnet). But it does leave the layout for any future specific NPC that gets confused for someone else. Thanks! Closing once more.
